### ISSUE TITLE
"can't pickle _thread.lock" in ResumableDatasetLoop with SubprocessRunner in Python 3

### ISSUE THREAD

**Issue by TaiSakuma** [alphatwirl/alphatwirl#57]
at 8db62fc2ad9a87c3169fea1d1089ad2f51d62172, a few commits after `v0.24.2`

```
Traceback (most recent call last):
  File "./bdphi-scripts/bdphiROC/twirl_mktbl_heppy.py", line 721, in <module>
    main()
  File "./bdphi-scripts/bdphiROC/twirl_mktbl_heppy.py", line 62, in main
    run(reader_collector_pairs)
  File "./bdphi-scripts/bdphiROC/twirl_mktbl_heppy.py", line 609, in run
    treeName='tree'
  File "./bdphi-scripts/external/atheppy/atheppy/fw.py", line 110, in run
    self._run(loop)
  File "./bdphi-scripts/external/atheppy/atheppy/fw.py", line 285, in _run
    loop()
  File "./bdphi-scripts/external/alphatwirl/alphatwirl/datasetloop/loop.py", line 60, in __call__
    pickle.dump(self.reader, f, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle _thread.lock objects
```

The error occures in `ResumableDatasetLoop`:
https://github.com/alphatwirl/alphatwirl/blob/8db62fc2ad9a87c3169fea1d1089ad2f51d62172/alphatwirl/datasetloop/loop.py#L52-L61

- This happens only in Python 3, not in Python 2.7
- This happens only in the parrallel mode `subprocess`, not in `htcondor`.

The `proc` in `SubprocessRunner` might not be picklable in Python 3:
https://github.com/alphatwirl/alphatwirl/blob/8db62fc2ad9a87c3169fea1d1089ad2f51d62172/alphatwirl/concurrently/SubprocessRunner.py#L44-L50

- can try to pickle before `self.reader.read(dataset)` or `self.reader.begin()`

**Comment by TaiSakuma** [comment]
- now pickle before start reading events 2eea376679478c5fb63262b77c3d8993bb4af650
- this is not covered by unit tests
